// <auto-generated/>
using System;

namespace CSharpCodeGenDemo
{
    public static partial class Program
    {
        static partial void HelloFrom(string name) =>
            Console.WriteLine($"Generator says: Hi from '{name}'");
    }
}
